'use strict'

const titles = [
	'Classroom A',
	'Lecture Hall 101',
	'Study Room 1',
	'Science Lab 4A',
	'Computer Lab B',
	'Library Annex',
	'Seminar Room 2',
	'Art Studio 3',
	'Music Room 5',
	'History Corner',
	'Math Center',
	'Reading Nook',
	'Writing Workshop',
	'Language Lab 6',
	'Physics Lab 3B',
	'Chemistry Classroom',
	'Biology Lab 7',
	'Geography Hub',
	'Astronomy Dome',
	'Theater Stage',
	'Psychology Lab',
	'Sociology Seminar',
	'Debate Chamber',
	'Robotics Lab',
	'Research Suite',
	'Innovation Studio',
	'Ethics Forum',
	'Philosophy Salon',
	'Economics Center',
	'Ethics Symposium',
	'Career Counseling',
	'Internship Office',
	'Graduation Hall',
	'Thesis Workspace',
	'Study Lounge',
	'Grad Student Lounge',
	'Exam Hall',
	'Tutoring Center',
	'Language Learning Lab',
	'Peer Mentor Room',
	'History Symposium',
	'Math Club Room',
	'Science Exploration',
	'Writing Center',
	'Creative Writing Studio',
	'Art Gallery',
	'Music Practice Room',
	'Drama Studio',
	'Biology Research Lab',
	'Chemistry Workshop',
	'Astronomy Observatory',
	'Theater Workshop',
	'Psychology Clinic',
	'Sociology Lab',
	'Debate Society',
	'Robotics Workshop',
	'Research Library',
	'Maker Space',
	'Academic Commons',
	'Ethics Library',
	'Philosophy Forum',
	'Economics Lecture Hall',
	'Academic Excellence Center',
	'Leadership Institute',
	'Career Development Center',
	'Alumni Lounge',
	'Graduation Auditorium',
	'Thesis Presentation Room',
	'Quiet Study Zone',
	'Grad Student Hub',
	'Exam Proctoring Center',
	'Peer Tutoring Lab',
	'History Archive',
	'Math Society Room',
	'Science Discovery Lab',
	'Writing Support Center',
	'Art Studio Workshop',
	'Music Recital Hall',
	'Drama Performance Stage',
	'Biology Ecology Lab',
	'Chemistry Materials Lab',
	'Astronomy Galaxy Room',
	'Theater Costume Studio',
	'Psychology Research Lab',
	'Sociology Discussion Room',
	'Debate Practice Hall',
	'Robotics Development Lab',
	'Research Collaboration Space',
	'Innovation Hub',
	'Ethics Roundtable',
	'Philosophy Seminar Space',
	'Economics Policy Center',
	'Academic Advising Lounge',
	'Leadership Training Room',
	'Career Coaching Office',
	'Alumni Networking Lounge',
	'Graduation Ceremony Hall',
	'Thesis Review Chamber',
	'Silent Study Zone',
	'Grad Student Hangout',
	'Exam Assistance Room',
	'Peer Tutoring Hub',
	'History Research Archive',
	'Math Problem-Solving Room',
	'Science Exploration Hub',
	'Writing Assistance Center',
	'Art Studio Gallery',
	'Music Practice Studio',
	'Drama Rehearsal Space',
	'Biology Lab Discovery',
	'Chemistry Lab Innovations',
	'Astronomy Observation Room',
	'Theater Design Studio',
	'Psychology Counseling Suite',
	'Sociology Research Lounge',
	'Debate Club Meeting Room',
	'Robotics Workshop',
	'Research Collaboration Hub',
	'Innovation Workshop',
	'Ethics Lecture Hall',
	'Philosophy Discussion Room',
	'Economics Research Space',
	'Academic Success Room',
	'Leadership Development Space',
	'Career Advancement Center',
	'Alumni Engagement Space',
	'Graduation Planning Office',
	'Thesis Presentation Chamber',
	'Silent Study Retreat',
	'Grad Student Collaboration Space',
	'Exam Preparation Zone',
	'Peer Tutoring Lounge',
	'History Symposium Room',
	'Math Society Meeting Space',
	'Science Lab Inquiry',
	'Writing Workshop',
	'Creative Writing Studio',
	'Art Studio Gallery',
	'Music Rehearsal Stage',
]

console.log(titles.length)

const shuffleArray = (array) => {
	for (let i = array.length - 1; i > 0; i--) {
		const j = Math.floor(Math.random() * (i + 1))
		;[array[i], array[j]] = [array[j], array[i]]
	}
	return array
}

exports.sessionTitles = shuffleArray(titles)
